name: build
on:
  push:
    branches:
      - master
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: set up go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: build
      run: go get -v ./... && go build -o checker -v ./app/

    - name: build and push image
      run: |
        docker build -t rbhz/http_checker:latest .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push rbhz/http_checker:latest
